import { GameConfig } from "../../gameConfig";
import type { DeepPartial } from "../../utils/util";
import { v2 } from "../../utils/v2";
import type { MapDef } from "../mapDefs";
import { MapId } from "../types/misc";

export const Main: MapDef = {
    mapId: MapId.Main,
    desc: {
        name: "Snow Duel (1v1)",
        icon: "img/loot/loot-throwable-snowball.svg",
        buttonCss: "btn-mode-snow",
        backgroundImg: "img/main_splash.png",
    },
    assets: {
        audio: [
            { name: "club_music_01", channel: "ambient" },
            { name: "club_music_02", channel: "ambient" },
            { name: "ambient_steam_01", channel: "ambient" },
            { name: "log_11", channel: "sfx" },
            { name: "log_12", channel: "sfx" },
        ],
        atlases: ["gradient", "loadout", "shared", "main"],
    },
    biome: {
        colors: {
            background: 0x081021,
            water: 0x0f2236,
            waterRipple: 0x416d8c,
            beach: 0x28323d,
            riverbank: 0x3b4b5b,
            grass: 0x2e3a4a,
            underground: 0x010205,
            playerSubmerge: 0x0f2236,
            playerGhillie: 0x4a5b6a,
        },
        valueAdjust: 0.9,
        sound: { riverShore: "sand" },
        particles: { camera: "" },
        tracerColors: {},
        airdrop: {
            planeImg: "map-plane-01.img",
            planeSound: "plane_01",
            airdropImg: "map-chute-01.img",
        },
    },
    gameMode: {
        maxPlayers: 2,
        killLeaderEnabled: true,
    },
    /* STRIP_FROM_PROD_CLIENT:START */
    gameConfig: {
        planes: {
            timings: [
                {
                    circleIdx: 1,
                    wait: 10,
                    options: { type: GameConfig.Plane.Airdrop },
                },
                {
                    circleIdx: 3,
                    wait: 2,
                    options: { type: GameConfig.Plane.Airdrop },
                },
            ],
            crates: [
                { name: "airdrop_crate_01", weight: 0 },
                { name: "airdrop_crate_02", weight: 0 },
            ],
        },
        bagSizes: {},
        bleedDamage: 2,
        bleedDamageMult: 1,
        defaultItems: {
            weapons: [
                { type: "spas12", ammo: 9999 },
                { type: "sv98", ammo: 9999 },
                { type: "fists", ammo: 0 },
                { type: "", ammo: 0 },
            ],
            helmet: "helmet03",
            chest: "chest03",
            backpack: "backpack03",
            scope: "8xscope",
            perks: [{ type: "endless_ammo", droppable: false }],
            inventory: {
                "12gauge": 9999,
                "762mm": 9999,
                "8xscope": 1,
                bandage: 20,
                healthkit: 4,
                soda: 8,
                painkiller: 4,
            },
        },
    },
    lootTable: {
        tier_world: [
            { name: "tier_guns", count: 1, weight: 0.29 },
            { name: "tier_ammo", count: 1, weight: 0.04 },
            { name: "tier_scopes", count: 1, weight: 0.15 },
            { name: "tier_armor", count: 1, weight: 0.1 },
            { name: "tier_medical", count: 1, weight: 0.17 },
            { name: "tier_throwables", count: 1, weight: 0.05 },
            { name: "tier_packs", count: 1, weight: 0.09 },
        ],
        tier_surviv: [
            { name: "tier_scopes", count: 1, weight: 0.15 },
            { name: "tier_armor", count: 1, weight: 0.1 },
            { name: "tier_medical", count: 1, weight: 0.17 },
            { name: "tier_throwables", count: 1, weight: 0.05 },
            { name: "tier_packs", count: 1, weight: 0.09 },
        ],
        tier_container: [
            { name: "tier_guns", count: 1, weight: 0.29 },
            { name: "tier_ammo", count: 1, weight: 0.04 },
            { name: "tier_scopes", count: 1, weight: 0.15 },
            { name: "tier_armor", count: 1, weight: 0.1 },
            { name: "tier_medical", count: 1, weight: 0.17 },
            { name: "tier_throwables", count: 1, weight: 0.05 },
            { name: "tier_packs", count: 1, weight: 0.09 },
            { name: "tier_outfits", count: 1, weight: 0.035 },
        ],
        tier_leaf_pile: [
            { name: "tier_ammo", count: 1, weight: 0.2 },
            { name: "tier_scopes", count: 1, weight: 0.2 },
            { name: "tier_armor", count: 1, weight: 0.2 },
            { name: "tier_medical", count: 1, weight: 0.2 },
            { name: "tier_throwables", count: 1, weight: 0.15 },
            { name: "tier_packs", count: 1, weight: 0.05 },
        ],
        tier_soviet: [
            { name: "tier_guns", count: 1, weight: 3 },
            { name: "tier_armor", count: 1, weight: 2 },
            { name: "tier_packs", count: 1, weight: 1 },
        ],
        tier_toilet: [
            { name: "tier_guns", count: 1, weight: 0.1 },
            { name: "tier_scopes", count: 1, weight: 0.05 },
            { name: "tier_medical", count: 1, weight: 0.6 },
            { name: "tier_throwables", count: 1, weight: 0.05 },
            { name: "tier_outfits", count: 1, weight: 0.025 },
        ],
        tier_scopes: [
            { name: "2xscope", count: 1, weight: 24 },
            { name: "4xscope", count: 1, weight: 5 },
            { name: "8xscope", count: 1, weight: 1 },
            { name: "15xscope", count: 1, weight: 0.02 },
        ],
        tier_armor: [
            { name: "helmet01", count: 1, weight: 9 },
            { name: "helmet02", count: 1, weight: 6 },
            { name: "helmet03", count: 1, weight: 0.2 },
            { name: "chest01", count: 1, weight: 15 },
            { name: "chest02", count: 1, weight: 6 },
            { name: "chest03", count: 1, weight: 0.2 },
        ],
        tier_packs: [
            { name: "backpack01", count: 1, weight: 15 },
            { name: "backpack02", count: 1, weight: 6 },
            { name: "backpack03", count: 1, weight: 0.2 },
        ],
        tier_medical: [
            { name: "bandage", count: 5, weight: 16 },
            { name: "healthkit", count: 1, weight: 4 },
            { name: "soda", count: 1, weight: 15 },
            { name: "painkiller", count: 1, weight: 5 },
        ],
        tier_throwables: [
            { name: "frag", count: 2, weight: 1 },
            { name: "smoke", count: 1, weight: 1 },
            { name: "mirv", count: 2, weight: 0.05 },
        ],
        tier_ammo: [
            { name: "9mm", count: 60, weight: 3 },
            { name: "762mm", count: 60, weight: 3 },
            { name: "556mm", count: 60, weight: 3 },
            { name: "12gauge", count: 10, weight: 3 },
        ],
        tier_ammo_crate: [
            { name: "9mm", count: 60, weight: 3 },
            { name: "762mm", count: 60, weight: 3 },
            { name: "556mm", count: 60, weight: 3 },
            { name: "12gauge", count: 10, weight: 3 },
            { name: "50AE", count: 21, weight: 1 },
            { name: "308sub", count: 5, weight: 1 },
            { name: "flare", count: 1, weight: 1 },
        ],
        tier_vending_soda: [
            { name: "soda", count: 1, weight: 1 },
            { name: "tier_ammo", count: 1, weight: 1 },
        ],
        tier_sv98: [{ name: "sv98", count: 1, weight: 1 }],
        tier_scopes_sniper: [
            { name: "4xscope", count: 1, weight: 5 },
            { name: "8xscope", count: 1, weight: 1 },
            { name: "15xscope", count: 1, weight: 0.02 },
        ],
        tier_mansion_floor: [{ name: "outfitCasanova", count: 1, weight: 1 }],
        tier_vault_floor: [{ name: "outfitJester", count: 1, weight: 1 }],
        tier_police_floor: [{ name: "outfitPrisoner", count: 1, weight: 1 }],
        tier_fragtastic: [
            { name: "", count: 1, weight: 1 },
            { name: "outfitFragtastic", count: 1, weight: 0.15 },
        ],
        tier_turkey_outfit: [
            { name: "", count: 1, weight: 1 },
            { name: "outfitTurkey", count: 1, weight: 0.05 },
        ],
        tier_chrys_01: [{ name: "outfitImperial", count: 1, weight: 1 }],
        tier_chrys_02: [{ name: "katana", count: 1, weight: 1 }],
        tier_chrys_03: [
            { name: "2xscope", count: 1, weight: 5 },
            { name: "4xscope", count: 1, weight: 5 },
            { name: "8xscope", count: 1, weight: 5 },
            { name: "15xscope", count: 1, weight: 0.1 },
        ],
        tier_chrys_case: [
            { name: "", count: 1, weight: 5 },
            { name: "tier_katanas", count: 1, weight: 3 },
            { name: "naginata", count: 1, weight: 1 },
        ],
        tier_crow_case_melee: [{ name: "crowbar", count: 1, weight: 1 }],
        tier_crow_case_skin: [
            { name: "outfitCarbonFiber", count: 1, weight: 1 },
            { name: "outfitDarkGloves", count: 1, weight: 1 },
        ],
        tier_eye_02: [{ name: "stonehammer", count: 1, weight: 1 }],
        tier_eye_block: [
            { name: "m9", count: 1, weight: 1 },
            { name: "ots38_dual", count: 1, weight: 1 },
            { name: "flare_gun", count: 1, weight: 1 },
            { name: "colt45", count: 1, weight: 1 },
            { name: "45acp", count: 1, weight: 1 },
            { name: "painkiller", count: 1, weight: 1 },
            { name: "m4a1", count: 1, weight: 1 },
            { name: "m249", count: 1, weight: 1 },
            { name: "awc", count: 1, weight: 1 },
            { name: "pkp", count: 1, weight: 1 },
        ],
        tier_eye_stone: [
            { name: "vector45", count: 1, weight: 1 },
            { name: "45acp", count: 1, weight: 1 },
            { name: "garand", count: 1, weight: 1 },
            { name: "strobe", count: 1, weight: 1 },
            { name: "healthkit", count: 1, weight: 1 },
            { name: "painkiller", count: 1, weight: 1 },
            { name: "m4a1", count: 1, weight: 0.7 },
            { name: "m249", count: 1, weight: 0.2 },
            { name: "scarssr", count: 1, weight: 0.1 },
            { name: "awc", count: 1, weight: 0.1 },
            { name: "pkp", count: 1, weight: 0.1 },
        ],
        tier_barn_melee: [{ name: "sledgehammer", count: 1, weight: 1 }],
        tier_chest_04: [
            { name: "p30l", count: 1, weight: 40 },
            { name: "p30l_dual", count: 1, weight: 1 },
        ],
        tier_woodaxe: [{ name: "woodaxe", count: 1, weight: 1 }],
        tier_club_melee: [{ name: "machete_taiga", count: 1, weight: 1 }],
        tier_guns: [
            { name: "famas", count: 1, weight: 0.9 },
            { name: "hk416", count: 1, weight: 4 },
            { name: "mk12", count: 1, weight: 0.1 },
            { name: "pkp", count: 1, weight: 0.005 },
            { name: "m249", count: 1, weight: 0.006 },
            { name: "ak47", count: 1, weight: 2.7 },
            { name: "scar", count: 1, weight: 0.01 },
            { name: "dp28", count: 1, weight: 0.5 },
            { name: "bar", count: 1, weight: 0.05 },
            { name: "mosin", count: 1, weight: 0.05 },
            { name: "m39", count: 1, weight: 0.1 },
            { name: "mp5", count: 1, weight: 10 },
            { name: "mac10", count: 1, weight: 6 },
            { name: "ump9", count: 1, weight: 3 },
            { name: "m870", count: 1, weight: 9 },
            { name: "m1100", count: 1, weight: 6 },
            { name: "mp220", count: 1, weight: 2 },
            { name: "saiga", count: 1, weight: 0.1 },
            { name: "ot38", count: 1, weight: 8 },
            { name: "m9", count: 1, weight: 19 },
            { name: "m93r", count: 1, weight: 5 },
            { name: "glock", count: 1, weight: 7 },
            { name: "deagle", count: 1, weight: 0.05 },
            { name: "vector", count: 1, weight: 0.01 },
            { name: "sv98", count: 1, weight: 0.01 },
            { name: "spas12", count: 1, weight: 1 },
            { name: "qbb97", count: 1, weight: 0.01 },
            { name: "flare_gun", count: 1, weight: 0.145 },
            { name: "flare_gun_dual", count: 1, weight: 0.0025 },
            { name: "groza", count: 1, weight: 0.8 },
            { name: "scout_elite", count: 1, weight: 0.1 },
            { name: "vss", count: 1, weight: 0.1 },
        ],
        tier_police: [
            { name: "scar", count: 1, weight: 0.5 },
            { name: "helmet03", count: 1, weight: 0.15 },
            { name: "chest03", count: 1, weight: 0.1 },
            { name: "backpack03", count: 1, weight: 0.25 },
        ],
        tier_ring_case: [
            { name: "grozas", count: 1, weight: 0.75 },
            { name: "ots38_dual", count: 1, weight: 0.15 },
            { name: "pkp", count: 1, weight: 0.1 },
            { name: "m9", count: 1, weight: 0.01 },
        ],
        tier_chest: [
            { name: "famas", count: 1, weight: 1.15 },
            { name: "hk416", count: 1, weight: 4 },
            { name: "mk12", count: 1, weight: 0.55 },
            { name: "m249", count: 1, weight: 0.07 },
            { name: "ak47", count: 1, weight: 4 },
            { name: "scar", count: 1, weight: 0.27 },
            { name: "dp28", count: 1, weight: 0.55 },
            { name: "bar", count: 1, weight: 0.27 },
            { name: "mosin", count: 1, weight: 0.55 },
            { name: "m39", count: 1, weight: 0.55 },
            { name: "saiga", count: 1, weight: 0.26 },
            { name: "mp220", count: 1, weight: 1.5 },
            { name: "deagle", count: 1, weight: 0.15 },
            { name: "vector", count: 1, weight: 0.1 },
            { name: "sv98", count: 1, weight: 0.1 },
            { name: "spas12", count: 1, weight: 1 },
            { name: "groza", count: 1, weight: 1.15 },
            { name: "helmet02", count: 1, weight: 1 },
            { name: "helmet03", count: 1, weight: 0.25 },
            { name: "chest02", count: 1, weight: 1 },
            { name: "chest03", count: 1, weight: 0.25 },
            { name: "4xscope", count: 1, weight: 0.5 },
            { name: "8xscope", count: 1, weight: 0.25 },
        ],
        tier_conch: [
            { name: "outfitAqua", count: 1, weight: 1 },
            { name: "outfitCoral", count: 1, weight: 1 },
        ],
        tier_noir_outfit: [{ name: "outfitNoir", count: 1, weight: 1 }],
        tier_khaki_outfit: [
            { name: "outfitKhaki", count: 1, weight: 20 },
            { name: "outfitParmaPrestige", count: 1, weight: 1 },
        ],
        tier_pirate_melee: [{ name: "hook", count: 1, weight: 1 }],
        tier_hatchet: [
            { name: "vector", count: 1, weight: 0.4 },
            { name: "bar", count: 1, weight: 0.25 },
            { name: "mp220", count: 1, weight: 0.15 },
            { name: "pkp", count: 1, weight: 0.01 },
            { name: "m249", count: 1, weight: 0.01 },
            { name: "m9", count: 1, weight: 0.01 },
        ],
        tier_lmgs: [
            { name: "dp28", count: 1, weight: 2 },
            { name: "bar", count: 1, weight: 1.5 },
            { name: "qbb97", count: 1, weight: 0.5 },
            { name: "m249", count: 1, weight: 0.05 },
            { name: "pkp", count: 1, weight: 0.05 },
        ],
        tier_shotguns: [
            { name: "spas12", count: 1, weight: 2 },
            { name: "mp220", count: 1, weight: 1.5 },
            { name: "m1100", count: 1, weight: 1 },
            { name: "m870", count: 1, weight: 1 },
            { name: "saiga", count: 1, weight: 0.15 },
            { name: "usas", count: 1, weight: 0.01 },
        ],
        tier_snipers: [
            { name: "model94", count: 1, weight: 6 },
            { name: "blr", count: 1, weight: 6 },
            { name: "scout_elite", count: 1, weight: 3 },
            { name: "mk12", count: 1, weight: 2 },
            { name: "m39", count: 1, weight: 2 },
            { name: "vss", count: 1, weight: 1.5 },
            { name: "mosin", count: 1, weight: 0.75 },
            { name: "mkg45", count: 1, weight: 0.75 },
            { name: "l86", count: 1, weight: 0.75 },
            { name: "svd", count: 1, weight: 0.75 },
            { name: "garand", count: 1, weight: 0.45 },
            { name: "scarssr", count: 1, weight: 0.15 },
            { name: "awc", count: 1, weight: 0.15 },
            { name: "sv98", count: 1, weight: 0.1 },
        ],
        tier_hatchet_melee: [
            { name: "fireaxe", count: 1, weight: 5 },
            { name: "tier_katanas", count: 1, weight: 3 },
            { name: "stonehammer", count: 1, weight: 1 },
        ],
        tier_pavilion: [
            { name: "naginata", count: 1, weight: 2 },
            { name: "pkp", count: 1, weight: 2 },
            { name: "dp28", count: 1, weight: 1 },
            { name: "bar", count: 1, weight: 1 },
            { name: "m9", count: 1, weight: 1 },
        ],
        tier_safe: [
            { name: "m9", count: 1, weight: 0.01 },
            { name: "fabricate", count: 1, weight: 1 },
            { name: "flak_jacket", count: 1, weight: 1 },
            { name: "explosive", count: 1, weight: 1 },
        ],
        tier_safe_throwables: [
            { name: "", count: 1, weight: 1 },
            { name: "strobe", count: 1, weight: 1 },
        ],
        tier_forest_helmet: [{ name: "helmet03_forest", count: 1, weight: 1 }],
        tier_outfits: [
            { name: "outfitCobaltShell", count: 1, weight: 0.2 },
            { name: "outfitRed", count: 1, weight: 0.2 },
            { name: "outfitWhite", count: 1, weight: 0.2 },
            { name: "outfitKeyLime", count: 1, weight: 0.15 },
            { name: "outfitWoodland", count: 1, weight: 0.1 },
            { name: "outfitCarbonFiber", count: 1, weight: 0.1 },
            { name: "outfitDarkGloves", count: 1, weight: 0.1 },
            { name: "outfitCamo", count: 1, weight: 0.1 },
            { name: "outfitGhillie", count: 1, weight: 0.01 },
        ],
        tier_egg_outfits: [
            { name: "outfitBarrel", count: 1, weight: 1 },
            { name: "outfitWoodBarrel", count: 1, weight: 1 },
            { name: "outfitStone", count: 1, weight: 1 },
            { name: "outfitSpringTree", count: 1, weight: 1 },
            { name: "outfitBush", count: 1, weight: 1 },
            { name: "outfitCrate", count: 1, weight: 1 },
            { name: "outfitTable", count: 1, weight: 1 },
            { name: "outfitSoviet", count: 1, weight: 1 },
            { name: "outfitOven", count: 1, weight: 1 },
            { name: "outfitRefrigerator", count: 1, weight: 1 },
            { name: "outfitVending", count: 1, weight: 1 },
            { name: "outfitToilet", count: 1, weight: 1 },
            { name: "outfitBushRiver", count: 1, weight: 1 },
            { name: "outfitCrab", count: 1, weight: 1 },
        ],
        tier_pirate_outfits: [{ name: "outfitRoyalFortune", count: 1, weight: 1 }],
        tier_islander_outfit: [{ name: "outfitIslander", count: 1, weight: 1 }],
        tier_imperial_outfit: [{ name: "outfitImperial", count: 1, weight: 1 }],
        tier_pineapple_outfit: [{ name: "outfitPineapple", count: 1, weight: 1 }],
        tier_tarkhany_outfit: [{ name: "outfitTarkhany", count: 1, weight: 1 }],
        tier_spetsnaz_outfit: [{ name: "outfitSpetsnaz", count: 1, weight: 1 }],
        tier_lumber_outfit: [{ name: "outfitLumber", count: 1, weight: 1 }],
        tier_verde_outfit: [{ name: "outfitVerde", count: 1, weight: 1 }],
        tier_coconut_outfit: [
            { name: "", count: 1, weight: 19 },
            { name: "outfitCoconut", count: 1, weight: 1 },
        ],
        tier_guns_common_scout: [
            { name: "glock_dual", count: 1, weight: 1 },
            { name: "ot38_dual", count: 1, weight: 1 },
            { name: "m93r_dual", count: 1, weight: 1 },
            { name: "deagle", count: 1, weight: 0.2 },
        ],
        tier_guns_common_sniper: [
            { name: "blr", count: 1, weight: 1 },
            { name: "mosin", count: 1, weight: 0.2 },
            { name: "scout_elite", count: 1, weight: 1 },
        ],
        tier_guns_common_healer: [
            { name: "mk12", count: 1, weight: 1 },
            { name: "m39", count: 1, weight: 1 },
            { name: "vss", count: 1, weight: 1 },
        ],
        tier_guns_common_demo: [
            { name: "m870", count: 1, weight: 1 },
            { name: "spas12", count: 1, weight: 0.5 },
            { name: "mp220", count: 1, weight: 1 },
        ],
        tier_guns_common_assault: [
            { name: "hk416", count: 1, weight: 1 },
            { name: "ak47", count: 1, weight: 1 },
            { name: "groza", count: 1, weight: 1 },
            { name: "famas", count: 1, weight: 1 },
        ],
        tier_guns_common_tank: [
            { name: "dp28", count: 1, weight: 1 },
            { name: "qbb97", count: 1, weight: 0.2 },
            { name: "bar", count: 1, weight: 0.5 },
        ],
        tier_guns_rare_scout: [
            { name: "ots38_dual", count: 1, weight: 1 },
            { name: "p30l_dual", count: 1, weight: 0.5 },
            { name: "deagle_dual", count: 1, weight: 0.5 },
        ],
        tier_guns_rare_sniper: [
            { name: "mosin", count: 1, weight: 1 },
            { name: "sv98", count: 1, weight: 0.1 },
            { name: "awc", count: 1, weight: 0.05 },
        ],
        tier_guns_rare_demo: [
            { name: "saiga", count: 1, weight: 1 },
            { name: "usas", count: 1, weight: 0.1 },
            { name: "m1014", count: 1, weight: 0.1 },
        ],
        tier_guns_rare_healer: [
            { name: "svd", count: 1, weight: 1 },
            { name: "l86", count: 1, weight: 1 },
            { name: "garand", count: 1, weight: 0.5 },
            { name: "scarssr", count: 1, weight: 0.05 },
        ],
        tier_guns_rare_assault: [
            { name: "scar", count: 1, weight: 1 },
            { name: "grozas", count: 1, weight: 1 },
            { name: "m4a1", count: 1, weight: 1 },
            { name: "an94", count: 1, weight: 0.5 },
        ],
        tier_guns_rare_tank: [
            { name: "qbb97", count: 1, weight: 1.3 },
            { name: "pkp", count: 1, weight: 0.1 },
            { name: "m249", count: 1, weight: 0.2 },
        ],
        tier_class_crate_mythic: [
            { name: "scavenger_adv", count: 1, weight: 1 },
            { name: "explosive", count: 1, weight: 1 },
            { name: "splinter", count: 1, weight: 1 },
        ],
        tier_scavenger_adv: [
            { name: "m9", count: 1, weight: 1 },
            { name: "ots38_dual", count: 1, weight: 1 },
            { name: "p30l_dual", count: 1, weight: 1 },
            { name: "saiga", count: 1, weight: 1 },
            { name: "deagle_dual", count: 1, weight: 1 },
            { name: "vector", count: 1, weight: 1 },
            { name: "scorpion", count: 1, weight: 1 },
            { name: "m4a1", count: 1, weight: 1 },
            { name: "garand", count: 1, weight: 1 },
            { name: "grozas", count: 1, weight: 1 },
            { name: "flare_gun", count: 1, weight: 1 },
            { name: "awc", count: 1, weight: 1 },
            { name: "scarssr", count: 1, weight: 1 },
            { name: "pkp", count: 1, weight: 1 },
            { name: "m249", count: 1, weight: 1 },
            { name: "sv98", count: 1, weight: 1 },
            { name: "pan", count: 1, weight: 1 },
            { name: "8xscope", count: 1, weight: 1 },
            { name: "15xscope", count: 1, weight: 1 },
            { name: "mirv", count: 4, weight: 1 },
            { name: "outfitGhillie", count: 1, weight: 1 },
            { name: "painkiller", count: 2, weight: 1 },
            { name: "healthkit", count: 1, weight: 1 },
            { name: "helmet03", count: 1, weight: 1 },
            { name: "chest03", count: 1, weight: 1 },
            { name: "backpack03", count: 1, weight: 1 },
        ],
        tier_pirate: [
            { name: "tier_ammo", count: 1, weight: 0.1 },
            { name: "tier_scopes", count: 1, weight: 0.1 },
            { name: "tier_armor", count: 1, weight: 0.05 },
            { name: "tier_medical", count: 1, weight: 0.25 },
            { name: "tier_throwables", count: 1, weight: 0.15 },
            { name: "tier_packs", count: 1, weight: 0.05 },
        ],
        tier_pirate_rare: [
            { name: "m9", count: 1, weight: 0.5 },
            { name: "m4a1", count: 1, weight: 1 },
            { name: "scorpion", count: 1, weight: 1 },
            { name: "scar", count: 1, weight: 1 },
            { name: "flare", count: 1, weight: 1 },
            { name: "garand", count: 1, weight: 0.75 },
            { name: "mosin", count: 1, weight: 0.5 },
            { name: "deagle", count: 1, weight: 1 },
            { name: "saiga", count: 1, weight: 1 },
            { name: "p30l_dual", count: 1, weight: 0.5 },
            { name: "deagle_dual", count: 1, weight: 0.5 },
            { name: "sv98", count: 1, weight: 0.3 },
            { name: "awc", count: 1, weight: 0.3 },
            { name: "m249", count: 1, weight: 0.25 },
        ],
        tier_airdrop_uncommon: [
            { name: "mk12", count: 1, weight: 2.5 },
            { name: "scar", count: 1, weight: 0.75 },
            { name: "bar", count: 1, weight: 1 },
            { name: "mosin", count: 1, weight: 1.5 },
            { name: "m39", count: 1, weight: 2.5 },
            { name: "saiga", count: 1, weight: 1 },
            { name: "deagle", count: 1, weight: 1 },
            { name: "vector", count: 1, weight: 1 },
            { name: "sv98", count: 1, weight: 0.5 },
            { name: "qbb97", count: 1, weight: 1.5 },
            { name: "m9", count: 1, weight: 0.01 },
            { name: "flare_gun", count: 1, weight: 0.5 },
            { name: "scout_elite", count: 1, weight: 2.5 },
            { name: "vss", count: 1, weight: 2.5 },
        ],
        tier_airdrop_rare: [
            { name: "garand", count: 1, weight: 6 },
            { name: "awc", count: 1, weight: 3 },
            { name: "pkp", count: 1, weight: 0.08 },
            { name: "m249", count: 1, weight: 0.1 },
            { name: "m4a1", count: 1, weight: 4 },
            { name: "scorpion", count: 1, weight: 5 },
            { name: "ots38_dual", count: 1, weight: 4.5 },
        ],
        tier_airdrop_mythic: [
            { name: "scarssr", count: 1, weight: 1 },
            { name: "usas", count: 1, weight: 0.5 },
            { name: "p30l_dual", count: 1, weight: 1 },
            { name: "awc", count: 1, weight: 0.1 },
            { name: "pkp", count: 1, weight: 0.3 },
            { name: "m249", count: 1, weight: 0.3 },
        ],
        tier_airdrop_ammo: [
            { name: "9mm", count: 30, weight: 3 },
            { name: "762mm", count: 30, weight: 3 },
            { name: "556mm", count: 30, weight: 3 },
            { name: "12gauge", count: 5, weight: 3 },
        ],
        tier_airdrop_outfits: [
            { name: "", count: 1, weight: 20 },
            { name: "outfitMeteor", count: 1, weight: 5 },
            { name: "outfitHeaven", count: 1, weight: 1 },
            { name: "outfitGhillie", count: 1, weight: 0.5 },
        ],
        tier_airdrop_throwables: [
            { name: "frag", count: 2, weight: 1 },
            { name: "mirv", count: 2, weight: 0.5 },
        ],
        tier_airdrop_melee: [
            { name: "", count: 1, weight: 19 },
            { name: "pan", count: 1, weight: 1 },
        ],
        tier_airdrop_armor: [
            { name: "helmet03", count: 1, weight: 1 },
            { name: "chest03", count: 1, weight: 1 },
            { name: "backpack03", count: 1, weight: 1 },
        ],
        tier_airdrop_scopes: [
            { name: "", count: 1, weight: 24 },
            { name: "4xscope", count: 1, weight: 5 },
            { name: "8xscope", count: 1, weight: 1 },
            { name: "15xscope", count: 1, weight: 0.02 },
        ],
        tier_katanas: [
            { name: "katana", count: 1, weight: 4 },
            { name: "katana_rusted", count: 1, weight: 4 },
            { name: "katana_orchid", count: 1, weight: 1 },
        ],
        tier_stonehammer: [{ name: "stonehammer", count: 1, weight: 1 }],
        tier_saloon: [
            { name: "vector45", count: 1, weight: 1 },
            { name: "mkg45", count: 1, weight: 1 },
        ],
        tier_cattle_crate: [
            { name: "m1a1", count: 1, weight: 1 },
            { name: "model94", count: 1, weight: 1 },
            { name: "colt45", count: 1, weight: 1 },
            { name: "outfitVerde", count: 1, weight: 0.1 },
            { name: "outfitDesertCamo", count: 1, weight: 0.3 },
        ],
        tier_cloud_02: [
            { name: "", count: 1, weight: 1 },
            { name: "outfitWheat", count: 1, weight: 0.3 },
        ],
        tier_pumpkin_candy: [{ name: "", weight: 1, count: 1 }],
        tier_pumpkin_perks: [{ name: "halloween_mystery", count: 1, weight: 1 }],
        tier_xp_uncommon: [
            { name: "xp_book_tallow", count: 1, weight: 1 },
            { name: "xp_book_greene", count: 1, weight: 1 },
            { name: "xp_book_parma", count: 1, weight: 1 },
            { name: "xp_book_nevelskoy", count: 1, weight: 1 },
            { name: "xp_book_rinzo", count: 1, weight: 1 },
            { name: "xp_book_kuga", count: 1, weight: 1 },
        ],
        tier_xp_rare: [
            { name: "xp_glasses", count: 1, weight: 0.1 },
            { name: "xp_compass", count: 1, weight: 0.1 },
            { name: "xp_stump", count: 1, weight: 0.1 },
            { name: "xp_bone", count: 1, weight: 0.1 },
        ],
        tier_xp_mythic: [{ name: "xp_donut", count: 1, weight: 0.01 }],
        tier_fruit_xp: [
            { name: "", count: 1, weight: 40 },
        ],
        tier_airdrop_xp: [
            { name: "", count: 1, weight: 15 },
        ],
        tier_halloween_mystery_perks: [
            { name: "trick_nothing", count: 1, weight: 1 },
            { name: "trick_size", count: 1, weight: 1 },
            { name: "trick_m9", count: 1, weight: 1 },
            { name: "trick_chatty", count: 1, weight: 1 },
            { name: "trick_drain", count: 1, weight: 1 },
            { name: "treat_9mm", count: 1, weight: 1 },
            { name: "treat_12g", count: 1, weight: 1 },
            { name: "treat_556", count: 1, weight: 1 },
            { name: "treat_762", count: 1, weight: 1 },
            { name: "treat_super", count: 1, weight: 0.1 },
        ],
        tier_faction_outfits: [
            { name: "outfitVerde", count: 1, weight: 1 },
            { name: "outfitWoodland", count: 1, weight: 1 },
            { name: "outfitKeyLime", count: 1, weight: 1 },
            { name: "outfitWhite", count: 1, weight: 1 },
            { name: "outfitCarbonFiber", count: 1, weight: 1 },
            { name: "outfitDarkGloves", count: 1, weight: 1 },
            { name: "outfitCamo", count: 1, weight: 1 },
        ],
        tier_airdrop_faction_outfits: [{ name: "outfitGhillie", count: 1, weight: 1 }],
        tier_airdrop_faction_melee: [{ name: "pan", count: 1, weight: 1 }],
        tier_perks: [
            { name: "firepower", count: 1, weight: 1 },
            { name: "windwalk", count: 1, weight: 1 },
            { name: "endless_ammo", count: 1, weight: 1 },
            { name: "steelskin", count: 1, weight: 1 },
            { name: "splinter", count: 1, weight: 1 },
            { name: "small_arms", count: 1, weight: 1 },
            { name: "takedown", count: 1, weight: 1 },
            { name: "field_medic", count: 1, weight: 1 },
            { name: "tree_climbing", count: 1, weight: 1 },
            { name: "scavenger", count: 1, weight: 1 },
            { name: "chambered", count: 1, weight: 1 },
            { name: "martyrdom", count: 1, weight: 1 },
            { name: "self_revive", count: 1, weight: 1 },
            { name: "bonus_9mm", count: 1, weight: 1 },
            { name: "bonus_45", count: 1, weight: 1 },
            { name: "high_velocity", count: 1, weight: 1 },
        ],
        tier_potato_perks: [
            { name: "", count: 1, weight: 25 },
            { name: "tier_perks", count: 1, weight: 1 },
        ],
        tier_knives: [],
    },
    mapGen: {
        map: {
            baseWidth: 50,
            baseHeight: 50,
            scale: { small: 1.1875, large: 1.28125 },
            extension: 112,
            shoreInset: 48,
            grassInset: 18,
            rivers: {
                lakes: [],
                weights: [
                    { weight: 0, widths: [4] },
                    { weight: 0, widths: [8] },
                    { weight: 0, widths: [8, 4] },
                    { weight: 0, widths: [16] },
                    { weight: 0, widths: [16, 8] },
                    { weight: 0, widths: [16, 8, 4] },
                    { weight: 1e-4, widths: [16, 16, 8, 6, 4] },
                ],
                smoothness: 0.45,
                spawnCabins: true,
                masks: [],
            },
        },
        places: [
            { name: "The Frozen Pit", pos: v2.create(0.53, 0.64) },
            { name: "", pos: v2.create(0.84, 0.18) },
            { name: "piesimp rules", pos: v2.create(0.15, 0.11) },
            { name: "ng0d sucks", pos: v2.create(0.25, 0.42) },
            { name: "w anh", pos: v2.create(0.4, 0.21) },
            { name: "larry pro dev", pos: v2.create(0.2, 0.425) },
            { name: "fuck cvzqti", pos: v2.create(0.81, 0.85) },
            { name: "fuck atul", pos: v2.create(0.21, 0.79) },
            { name: "w saer", pos: v2.create(0.73, 0.47) },
            { name: "", pos: v2.create(0.53, 0.25) },
        ],
        bridgeTypes: {
            medium: "bridge_md_structure_01",
            large: "bridge_lg_structure_01",
            xlarge: "",
        },
        customSpawnRules: {
            locationSpawns: [
                {
                    type: "club_complex_01",
                    pos: v2.create(0, 0),
                    rad: 0,
                    retryOnFailure: false,
                },
            ],
            placeSpawns: ["warehouse_01", "house_red_01", "house_red_02", "barn_01"],
        },
        densitySpawns: [
            {
                stone_01: 0,
                barrel_01: 0,
                silo_01: 0,
                crate_01: 0,
                crate_02: 0,
                crate_03: 0,
                bush_01: 0,
                cache_06: 0,
                tree_01: 0,
                tree_13: 0,
                hedgehog_01: 0,
                container_01: 0,
                container_02: 0,
                container_03: 0,
                container_04: 0,
                shack_01: 0,
                outhouse_01: 0,
                loot_tier_1: 0,
                loot_tier_beach: 0,
            },
        ],
        fixedSpawns: [
            {
                warehouse_01: { small: 0, large: 0 },
                warehouse_03: 0,
                house_red_01: { small: 0, large: 0 },
                house_red_02: { small: 0, large: 0 },
                barn_01: { small: 0, large: 0 },
                barn_02: 0,
                hut_01: 1,
                hut_02: 1,
                hut_03: 1,
                shack_03a: 0,
                shack_03b: { small: 0, large: 0 },
                greenhouse_01: 0,
                cache_01: 0,
                cache_02: 0,
                cache_07: 0,
                bunker_structure_01: { odds: 0 },
                bunker_structure_02: 0,
                bunker_structure_03: 0,
                bunker_structure_04: 0,
                bunker_structure_05: 0,
                warehouse_complex_01: 0,
                chest_01: 0,
                chest_03: { odds: 0 },
                mil_crate_02: { odds: 0 },
                tree_02: 0,
                teahouse_complex_01su: { small: 0, large: 0 },
                stone_04: 0,
            },
        ],
        randomSpawns: [
            {
                spawns: ["mansion_structure_01", "police_01", "bank_01"],
                choose: 0,
            },
        ],
        spawnReplacements: [{}],
        importantSpawns: ["club_complex_01"],
    },
    /* STRIP_FROM_PROD_CLIENT:END */
};

export type PartialMapDef = DeepPartial<MapDef>;
